version: '3.8'

services:
  psql:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - psql_volume:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate:v4.17.0
    entrypoint:
      - migrate
      - -path
      - migrations/
      - -database
      - postgres://${DB_USERNAME}:${DB_PASSWORD}@psql:5432/pismodb?sslmode=disable
      - -verbose
      - up
    volumes:
      - ./migrations:/migrations
    depends_on:
      - psql

volumes:
  psql_volume:
